### ISSUE TITLE
试用过程中的一些问题

### ISSUE THREAD

**Issue by BuptStEve** [midwayjs/midway-component#37]
翻了下源码，设置的这行还被注释了...

https://github.com/midwayjs/midway-component/blob/2ae27cadf5f9f31c1a603a7316fb42e3b895bdac/packages/swagger/src/lib/generator.ts#L103

**Comment by BuptStEve** [comment]
好像也没有写 servers 字段的地方，感觉可以在接收配置的时候都读取进来...
https://swagger.io/specification/

![image](https://user-images.githubusercontent.com/11501493/137688093-b5cfc621-55dd-4734-a025-9e34133e4a68.png)

**Comment by BuptStEve** [comment]
schema 的生成似乎写成返回值的话并不会自动生成

**Comment by czy88840616** [comment]
你好，我们将在近期将 swagger 组件迁移到 midway 主库，并进行重写。
